### PR TITLE
fix: hide statusbar when showing on iOS 13 so that it does not cover the banner

### PR DESCRIPTION
**Pull request by zskamljic**
Fix for issue #110

### CODE REVIEW

**Comment by ezisazis** [comment]
:+1:

**Comment by bruno01989** [comment]
Thanks for the fix!

Looking forward to seeing this getting merged soon 👍

**Comment by gajdatsy** [comment]
Wow, great! Keep up the good work 👍

**Comment by omate94** [comment]
👍

**Comment by calimarkus** [comment]
Thank you, I just merged it.

**Pull request merged**
